// Auto-generated by scripts/build-docs-manifest.ts
// Do not edit manually.

export interface DocArticle {
  slug: string
  title: string
  group: string
  order: number
  file: string
  section: 'getting-started' | 'syntax' | 'stdlib'
}

export interface DocGroup {
  title: string
  items: { slug: string; title: string }[]
}

export interface DocManifest {
  'getting-started': DocGroup[]
  syntax: DocGroup[]
  stdlib: DocGroup[]
  articles: Record<string, DocArticle>
}

const manifest: DocManifest = {
  "getting-started": [
    {
      "title": "Getting Started",
      "items": [
        {
          "slug": "shardscript-philosophy",
          "title": "ShardScript Philosophy"
        },
        {
          "slug": "runtime-architecture",
          "title": "Runtime Architecture"
        },
        {
          "slug": "installation-and-setup",
          "title": "Installation & Setup"
        }
      ]
    }
  ],
  "syntax": [
    {
      "title": "Fundamentals",
      "items": [
        {
          "slug": "variables-and-types",
          "title": "Variables and Types"
        },
        {
          "slug": "type-inference",
          "title": "Type Inference"
        },
        {
          "slug": "primitive-types",
          "title": "Primitive Types"
        },
        {
          "slug": "operators",
          "title": "Operators"
        },
        {
          "slug": "strings-and-interpolation",
          "title": "Strings and Interpolation"
        },
        {
          "slug": "arrays",
          "title": "Arrays"
        },
        {
          "slug": "lists-and-dictionaries",
          "title": "Lists and Dictionaries"
        }
      ]
    },
    {
      "title": "Control Flow",
      "items": [
        {
          "slug": "conditionals",
          "title": "Conditionals"
        },
        {
          "slug": "loops",
          "title": "Loops"
        },
        {
          "slug": "switch-expressions",
          "title": "switch Expressions"
        },
        {
          "slug": "exceptions",
          "title": "Exceptions and Error Handling"
        },
        {
          "slug": "deferred-execution",
          "title": "Deferred Execution"
        }
      ]
    },
    {
      "title": "Object-Oriented Programming",
      "items": [
        {
          "slug": "classes",
          "title": "Classes"
        },
        {
          "slug": "fields-and-properties",
          "title": "Fields and Properties"
        },
        {
          "slug": "methods",
          "title": "Methods"
        },
        {
          "slug": "constructors",
          "title": "Constructors and Initialization"
        },
        {
          "slug": "interfaces",
          "title": "Interfaces and Abstractions"
        },
        {
          "slug": "extension-methods",
          "title": "Extension Methods"
        },
        {
          "slug": "generics",
          "title": "Generic Types"
        }
      ]
    },
    {
      "title": "Resource Management",
      "items": [
        {
          "slug": "garbage-collection",
          "title": "Automatic Memory Management"
        },
        {
          "slug": "idisposable",
          "title": "Deterministic Disposal"
        }
      ]
    },
    {
      "title": "Asynchronous Programming",
      "items": [
        {
          "slug": "cooperative-multitasking",
          "title": "Cooperative Multitasking"
        },
        {
          "slug": "async-functions",
          "title": "Async Functions"
        },
        {
          "slug": "await-and-state-machines",
          "title": "Await and State Machines"
        },
        {
          "slug": "task-and-valuetask",
          "title": "Task and ValueTask"
        },
        {
          "slug": "cancellation-tokens",
          "title": "Cancellation Tokens"
        }
      ]
    },
    {
      "title": "Internals",
      "items": [
        {
          "slug": "typeshape-and-slots",
          "title": "TypeShape and Slots"
        },
        {
          "slug": "async-state-machine-lowering",
          "title": "Async State Machine Lowering"
        }
      ]
    },
    {
      "title": "Functional Programming",
      "items": [
        {
          "slug": "functions-and-delegates",
          "title": "Functions and Delegates"
        },
        {
          "slug": "lambda-expressions",
          "title": "Lambda Expressions"
        },
        {
          "slug": "closures",
          "title": "Closures"
        }
      ]
    }
  ],
  "stdlib": [
    {
      "title": "SHARD.MATH",
      "items": [
        {
          "slug": "basic-math",
          "title": "Basic Math"
        },
        {
          "slug": "trigonometry-and-logarithms",
          "title": "Trigonometry & Logarithms"
        },
        {
          "slug": "random-number-generation",
          "title": "Random Number Generation"
        }
      ]
    }
  ],
  "articles": {
    "shardscript-philosophy": {
      "slug": "shardscript-philosophy",
      "title": "ShardScript Philosophy",
      "group": "Getting Started",
      "order": 1,
      "file": "getting-started/01-philosophy.mdx",
      "section": "getting-started"
    },
    "runtime-architecture": {
      "slug": "runtime-architecture",
      "title": "Runtime Architecture",
      "group": "Getting Started",
      "order": 2,
      "file": "getting-started/02-runtime-architecture.mdx",
      "section": "getting-started"
    },
    "installation-and-setup": {
      "slug": "installation-and-setup",
      "title": "Installation & Setup",
      "group": "Getting Started",
      "order": 3,
      "file": "getting-started/03-installation-and-setup.mdx",
      "section": "getting-started"
    },
    "variables-and-types": {
      "slug": "variables-and-types",
      "title": "Variables and Types",
      "group": "Fundamentals",
      "order": 1,
      "file": "syntax/fundamentals/01-variables-and-types.mdx",
      "section": "syntax"
    },
    "type-inference": {
      "slug": "type-inference",
      "title": "Type Inference",
      "group": "Fundamentals",
      "order": 2,
      "file": "syntax/fundamentals/02-type-inference.mdx",
      "section": "syntax"
    },
    "primitive-types": {
      "slug": "primitive-types",
      "title": "Primitive Types",
      "group": "Fundamentals",
      "order": 3,
      "file": "syntax/fundamentals/03-primitive-types.mdx",
      "section": "syntax"
    },
    "operators": {
      "slug": "operators",
      "title": "Operators",
      "group": "Fundamentals",
      "order": 4,
      "file": "syntax/fundamentals/04-operators.mdx",
      "section": "syntax"
    },
    "strings-and-interpolation": {
      "slug": "strings-and-interpolation",
      "title": "Strings and Interpolation",
      "group": "Fundamentals",
      "order": 5,
      "file": "syntax/fundamentals/05-strings-and-interpolation.mdx",
      "section": "syntax"
    },
    "arrays": {
      "slug": "arrays",
      "title": "Arrays",
      "group": "Fundamentals",
      "order": 6,
      "file": "syntax/fundamentals/06-arrays.mdx",
      "section": "syntax"
    },
    "lists-and-dictionaries": {
      "slug": "lists-and-dictionaries",
      "title": "Lists and Dictionaries",
      "group": "Fundamentals",
      "order": 7,
      "file": "syntax/fundamentals/07-lists-and-dictionaries.mdx",
      "section": "syntax"
    },
    "conditionals": {
      "slug": "conditionals",
      "title": "Conditionals",
      "group": "Control Flow",
      "order": 1,
      "file": "syntax/control-flow/01-conditionals.mdx",
      "section": "syntax"
    },
    "loops": {
      "slug": "loops",
      "title": "Loops",
      "group": "Control Flow",
      "order": 2,
      "file": "syntax/control-flow/02-loops.mdx",
      "section": "syntax"
    },
    "switch-expressions": {
      "slug": "switch-expressions",
      "title": "switch Expressions",
      "group": "Control Flow",
      "order": 3,
      "file": "syntax/control-flow/03-switch-expressions.mdx",
      "section": "syntax"
    },
    "exceptions": {
      "slug": "exceptions",
      "title": "Exceptions and Error Handling",
      "group": "Control Flow",
      "order": 4,
      "file": "syntax/control-flow/04-exceptions.mdx",
      "section": "syntax"
    },
    "deferred-execution": {
      "slug": "deferred-execution",
      "title": "Deferred Execution",
      "group": "Control Flow",
      "order": 5,
      "file": "syntax/control-flow/05-deferred-execution.mdx",
      "section": "syntax"
    },
    "classes": {
      "slug": "classes",
      "title": "Classes",
      "group": "Object-Oriented Programming",
      "order": 1,
      "file": "syntax/object-oriented/01-classes.mdx",
      "section": "syntax"
    },
    "fields-and-properties": {
      "slug": "fields-and-properties",
      "title": "Fields and Properties",
      "group": "Object-Oriented Programming",
      "order": 2,
      "file": "syntax/object-oriented/02-fields-and-properties.mdx",
      "section": "syntax"
    },
    "methods": {
      "slug": "methods",
      "title": "Methods",
      "group": "Object-Oriented Programming",
      "order": 3,
      "file": "syntax/object-oriented/03-methods.mdx",
      "section": "syntax"
    },
    "constructors": {
      "slug": "constructors",
      "title": "Constructors and Initialization",
      "group": "Object-Oriented Programming",
      "order": 4,
      "file": "syntax/object-oriented/04-constructors.mdx",
      "section": "syntax"
    },
    "interfaces": {
      "slug": "interfaces",
      "title": "Interfaces and Abstractions",
      "group": "Object-Oriented Programming",
      "order": 5,
      "file": "syntax/object-oriented/05-interfaces.mdx",
      "section": "syntax"
    },
    "extension-methods": {
      "slug": "extension-methods",
      "title": "Extension Methods",
      "group": "Object-Oriented Programming",
      "order": 6,
      "file": "syntax/object-oriented/06-extension-methods.mdx",
      "section": "syntax"
    },
    "generics": {
      "slug": "generics",
      "title": "Generic Types",
      "group": "Object-Oriented Programming",
      "order": 7,
      "file": "syntax/object-oriented/07-generics.mdx",
      "section": "syntax"
    },
    "lambda-expressions": {
      "slug": "lambda-expressions",
      "title": "Lambda Expressions",
      "group": "Functional Programming",
      "order": 2,
      "file": "syntax/functional/02-lambda-expressions.mdx",
      "section": "syntax"
    },
    "closures": {
      "slug": "closures",
      "title": "Closures",
      "group": "Functional Programming",
      "order": 3,
      "file": "syntax/functional/03-closures.mdx",
      "section": "syntax"
    },
    "functions-and-delegates": {
      "slug": "functions-and-delegates",
      "title": "Functions and Delegates",
      "group": "Functional Programming",
      "order": 1,
      "file": "syntax/functional/01-functions-and-delegates.mdx",
      "section": "syntax"
    },
    "garbage-collection": {
      "slug": "garbage-collection",
      "title": "Automatic Memory Management",
      "group": "Resource Management",
      "order": 1,
      "file": "syntax/resource-management/01-garbage-collection.mdx",
      "section": "syntax"
    },
    "idisposable": {
      "slug": "idisposable",
      "title": "Deterministic Disposal",
      "group": "Resource Management",
      "order": 2,
      "file": "syntax/resource-management/02-idisposable.mdx",
      "section": "syntax"
    },
    "cooperative-multitasking": {
      "slug": "cooperative-multitasking",
      "title": "Cooperative Multitasking",
      "group": "Asynchronous Programming",
      "order": 1,
      "file": "syntax/async/01-cooperative-multitasking.mdx",
      "section": "syntax"
    },
    "async-functions": {
      "slug": "async-functions",
      "title": "Async Functions",
      "group": "Asynchronous Programming",
      "order": 2,
      "file": "syntax/async/02-async-functions.mdx",
      "section": "syntax"
    },
    "await-and-state-machines": {
      "slug": "await-and-state-machines",
      "title": "Await and State Machines",
      "group": "Asynchronous Programming",
      "order": 3,
      "file": "syntax/async/03-await-and-state-machines.mdx",
      "section": "syntax"
    },
    "task-and-valuetask": {
      "slug": "task-and-valuetask",
      "title": "Task and ValueTask",
      "group": "Asynchronous Programming",
      "order": 4,
      "file": "syntax/async/04-task-and-valuetask.mdx",
      "section": "syntax"
    },
    "cancellation-tokens": {
      "slug": "cancellation-tokens",
      "title": "Cancellation Tokens",
      "group": "Asynchronous Programming",
      "order": 5,
      "file": "syntax/async/05-cancellation-tokens.mdx",
      "section": "syntax"
    },
    "typeshape-and-slots": {
      "slug": "typeshape-and-slots",
      "title": "TypeShape and Slots",
      "group": "Internals",
      "order": 1,
      "file": "syntax/internals/01-typeshape-and-slots.mdx",
      "section": "syntax"
    },
    "async-state-machine-lowering": {
      "slug": "async-state-machine-lowering",
      "title": "Async State Machine Lowering",
      "group": "Internals",
      "order": 2,
      "file": "syntax/internals/02-async-state-machine-lowering.mdx",
      "section": "syntax"
    },
    "basic-math": {
      "slug": "basic-math",
      "title": "Basic Math",
      "group": "SHARD.MATH",
      "order": 1,
      "file": "stdlib/math/01-basic-math.mdx",
      "section": "stdlib"
    },
    "random-number-generation": {
      "slug": "random-number-generation",
      "title": "Random Number Generation",
      "group": "SHARD.MATH",
      "order": 3,
      "file": "stdlib/math/02-random.mdx",
      "section": "stdlib"
    },
    "trigonometry-and-logarithms": {
      "slug": "trigonometry-and-logarithms",
      "title": "Trigonometry & Logarithms",
      "group": "SHARD.MATH",
      "order": 2,
      "file": "stdlib/math/02-trigonometry-and-logarithms.mdx",
      "section": "stdlib"
    }
  }
}

export default manifest
