// Auto-generated by scripts/build-docs-manifest.ts
// Do not edit manually.

export interface DocArticle {
  slug: string
  title: string
  group: string
  groupOrder: number
  order: number
  file: string
  section: 'getting-started' | 'syntax' | 'stdlib' | 'library-building'
}

export interface DocGroup {
  title: string
  items: { slug: string; title: string }[]
}

export interface DocManifest {
  'getting-started': DocGroup[]
  syntax: DocGroup[]
  stdlib: DocGroup[]
  'library-building': DocGroup[]
  articles: Record<string, DocArticle>
}

const manifest: DocManifest = {
  "getting-started": [
    {
      "title": "Getting Started",
      "items": [
        {
          "slug": "shardscript-philosophy",
          "title": "ShardScript Philosophy"
        },
        {
          "slug": "runtime-architecture",
          "title": "Runtime Architecture"
        },
        {
          "slug": "installation-and-setup",
          "title": "Installation & Setup"
        }
      ]
    }
  ],
  "syntax": [
    {
      "title": "Fundamentals",
      "items": [
        {
          "slug": "variables-and-types",
          "title": "Variables and Types"
        },
        {
          "slug": "type-inference",
          "title": "Type Inference"
        },
        {
          "slug": "primitive-types",
          "title": "Primitive Types"
        },
        {
          "slug": "enums",
          "title": "Enums"
        },
        {
          "slug": "operators",
          "title": "Operators"
        },
        {
          "slug": "strings-and-interpolation",
          "title": "Strings and Interpolation"
        },
        {
          "slug": "arrays",
          "title": "Arrays"
        },
        {
          "slug": "lists-and-dictionaries",
          "title": "Lists and Dictionaries"
        }
      ]
    },
    {
      "title": "Control Flow",
      "items": [
        {
          "slug": "conditionals",
          "title": "Conditionals"
        },
        {
          "slug": "loops",
          "title": "Loops"
        },
        {
          "slug": "switch-expressions",
          "title": "switch Expressions"
        },
        {
          "slug": "exceptions",
          "title": "Exceptions and Error Handling"
        },
        {
          "slug": "deferred-execution",
          "title": "Deferred Execution"
        }
      ]
    },
    {
      "title": "Object-Oriented Programming",
      "items": [
        {
          "slug": "classes",
          "title": "Classes"
        },
        {
          "slug": "fields-and-properties",
          "title": "Fields and Properties"
        },
        {
          "slug": "methods",
          "title": "Methods"
        },
        {
          "slug": "constructors",
          "title": "Constructors and Initialization"
        },
        {
          "slug": "interfaces",
          "title": "Interfaces and Abstractions"
        },
        {
          "slug": "extension-methods",
          "title": "Extension Methods"
        },
        {
          "slug": "generics",
          "title": "Generic Types"
        },
        {
          "slug": "operator-overloading",
          "title": "Operator Overloading"
        }
      ]
    },
    {
      "title": "Functional Programming",
      "items": [
        {
          "slug": "functions-and-delegates",
          "title": "Functions and Delegates"
        },
        {
          "slug": "lambda-expressions",
          "title": "Lambda Expressions"
        },
        {
          "slug": "closures",
          "title": "Closures"
        }
      ]
    },
    {
      "title": "Resource Management",
      "items": [
        {
          "slug": "garbage-collection",
          "title": "Automatic Memory Management"
        },
        {
          "slug": "idisposable",
          "title": "Deterministic Disposal"
        }
      ]
    },
    {
      "title": "Asynchronous Programming",
      "items": [
        {
          "slug": "cooperative-multitasking",
          "title": "Cooperative Multitasking"
        },
        {
          "slug": "async-functions",
          "title": "Async Functions"
        },
        {
          "slug": "await-and-state-machines",
          "title": "Await and State Machines"
        },
        {
          "slug": "task-and-valuetask",
          "title": "Task and ValueTask"
        },
        {
          "slug": "cancellation-tokens",
          "title": "Cancellation Tokens"
        }
      ]
    }
  ],
  "stdlib": [
    {
      "title": "SHARD.MATH",
      "items": [
        {
          "slug": "basic-math",
          "title": "Basic Math"
        },
        {
          "slug": "trigonometry-and-logarithms",
          "title": "Trigonometry & Logarithms"
        },
        {
          "slug": "random-number-generation",
          "title": "Random Number Generation"
        }
      ]
    },
    {
      "title": "SHARD.ENVIRONMENT",
      "items": [
        {
          "slug": "environment",
          "title": "Environment"
        }
      ]
    },
    {
      "title": "SHARD.DEBUG",
      "items": [
        {
          "slug": "developer-tools",
          "title": "Developer Tools"
        },
        {
          "slug": "vm-inspection",
          "title": "VM Inspection"
        }
      ]
    },
    {
      "title": "SHARD.COLLECTIONS",
      "items": [
        {
          "slug": "ienumerable-and-ienumerator",
          "title": "IEnumerable & IEnumerator"
        },
        {
          "slug": "list",
          "title": "List<T>"
        },
        {
          "slug": "dictionary",
          "title": "Dictionary<K, V>"
        },
        {
          "slug": "queue-and-stack",
          "title": "Queue and Stack"
        }
      ]
    },
    {
      "title": "SHARD.JSON",
      "items": [
        {
          "slug": "json-serializer",
          "title": "JsonSerializer"
        },
        {
          "slug": "json-node",
          "title": "JsonNode"
        }
      ]
    },
    {
      "title": "SHARD.STREAMS",
      "items": [
        {
          "slug": "stream-interfaces",
          "title": "Stream Interfaces"
        },
        {
          "slug": "memory-stream",
          "title": "MemoryStream"
        },
        {
          "slug": "stream-reader-writer",
          "title": "StreamReader / StreamWriter"
        },
        {
          "slug": "binary-reader-writer",
          "title": "BinaryReader / BinaryWriter"
        }
      ]
    },
    {
      "title": "SHARD.FILESYSTEM",
      "items": [
        {
          "slug": "file-and-path",
          "title": "File & Path"
        },
        {
          "slug": "directory-and-directoryinfo",
          "title": "Directory & DirectoryInfo"
        },
        {
          "slug": "path-concatenation",
          "title": "Path Concatenation"
        }
      ]
    },
    {
      "title": "SHARD.SUBPROCESS",
      "items": [
        {
          "slug": "process-and-processstartinfo",
          "title": "Process & ProcessStartInfo"
        },
        {
          "slug": "subprocess-io-and-lifecycle",
          "title": "I/O & Lifecycle"
        }
      ]
    },
    {
      "title": "SHARD.ASYNC",
      "items": [
        {
          "slug": "task-completion-source",
          "title": "TaskCompletionSource<T>"
        },
        {
          "slug": "cancellation-token-and-source",
          "title": "CancellationToken & CancellationTokenSource"
        }
      ]
    },
    {
      "title": "SHARD.INTEROP",
      "items": [
        {
          "slug": "native-interop",
          "title": "Native Interop"
        }
      ]
    },
    {
      "title": "SHARD.HTTP",
      "items": [
        {
          "slug": "http-client",
          "title": "HttpClient"
        },
        {
          "slug": "http-server",
          "title": "HttpServer"
        }
      ]
    },
    {
      "title": "SHARD.SOCKET",
      "items": [
        {
          "slug": "tcp-sockets",
          "title": "TCP Sockets"
        }
      ]
    },
    {
      "title": "SHARD.REFLECTION",
      "items": [
        {
          "slug": "type-introspection",
          "title": "Type Introspection"
        }
      ]
    }
  ],
  "library-building": [
    {
      "title": "Getting Started",
      "items": [
        {
          "slug": "native-library-overview",
          "title": "Native Libraries Overview"
        },
        {
          "slug": "your-first-shard-cpp-library",
          "title": "Your First Native Library"
        },
        {
          "slug": "library-build-setup",
          "title": "Build Setup & CMake Integration"
        }
      ]
    },
    {
      "title": "Core API & Entry Point",
      "items": [
        {
          "slug": "shardlib-entrypoint",
          "title": "SHARDLIB_GETMETADATA & SHARDLIB_ENTRYPOINT"
        },
        {
          "slug": "headers-quick-reference",
          "title": "Header Reference"
        },
        {
          "slug": "accessibility-and-linking",
          "title": "Accessibility & Linking Values"
        }
      ]
    },
    {
      "title": "SymbolBuilder Types",
      "items": [
        {
          "slug": "namespace-symbol-builder",
          "title": "NamespaceSymbol Builder"
        },
        {
          "slug": "class-symbol-builder",
          "title": "ClassSymbol Builder"
        },
        {
          "slug": "struct-symbol-builder",
          "title": "StructSymbol Builder"
        },
        {
          "slug": "interface-symbol-builder",
          "title": "InterfaceSymbol Builder"
        },
        {
          "slug": "enum-symbol-builder",
          "title": "EnumSymbol Builder"
        },
        {
          "slug": "method-symbol-builder",
          "title": "MethodSymbol Builder"
        },
        {
          "slug": "constructor-symbol-builder",
          "title": "ConstructorSymbol Builder"
        },
        {
          "slug": "property-symbol-builder",
          "title": "PropertySymbol Builder"
        },
        {
          "slug": "indexer-symbol-builder",
          "title": "IndexatorSymbol Builder"
        },
        {
          "slug": "operator-symbol-builder",
          "title": "OperatorSymbol Builder"
        }
      ]
    },
    {
      "title": "Runtime Callback Contract",
      "items": [
        {
          "slug": "callback-contract-overview",
          "title": "The Native Callback Contract"
        },
        {
          "slug": "reading-arguments",
          "title": "Reading Arguments"
        },
        {
          "slug": "returning-values",
          "title": "Returning Values"
        },
        {
          "slug": "working-with-objects",
          "title": "Working with Objects"
        },
        {
          "slug": "working-with-fields",
          "title": "Working with Fields"
        },
        {
          "slug": "working-with-arrays",
          "title": "Working with Arrays"
        },
        {
          "slug": "garbage-collection-rules",
          "title": "Garbage Collection Rules"
        },
        {
          "slug": "native-callback-helpers",
          "title": "Native Callback Helpers"
        }
      ]
    },
    {
      "title": "Advanced Topics",
      "items": [
        {
          "slug": "generic-types-and-type-parameters",
          "title": "Generic Types & Type Parameters"
        },
        {
          "slug": "async-await-native",
          "title": "Async / Await in Native Libraries"
        },
        {
          "slug": "inter-library-dependencies",
          "title": "Inter-Library Dependencies"
        },
        {
          "slug": "reflection-style-lookups",
          "title": "Reflection-Style Lookups"
        },
        {
          "slug": "native-handles-and-object-lifetime",
          "title": "Native Handles, nint & Object Lifetime"
        },
        {
          "slug": "async-helpers-reference",
          "title": "Async Helpers Reference"
        },
        {
          "slug": "native-helpers-reference",
          "title": "Native Helpers Reference"
        }
      ]
    },
    {
      "title": "Best Practices & Troubleshooting",
      "items": [
        {
          "slug": "design-best-practices",
          "title": "Design Best Practices"
        },
        {
          "slug": "troubleshooting",
          "title": "Common Problems & Solutions"
        }
      ]
    },
    {
      "title": "Example Projects & Patterns",
      "items": [
        {
          "slug": "example-math-library",
          "title": "Example: shard.math"
        },
        {
          "slug": "example-generic-collections",
          "title": "Example: shard.collections"
        },
        {
          "slug": "example-async-io",
          "title": "Example: File/Stream I/O"
        },
        {
          "slug": "example-native-handle-wrapper",
          "title": "Example: Wrapping a C++ Class with nint & IDisposable"
        },
        {
          "slug": "example-http-client-server",
          "title": "Example: HTTP Client/Server"
        }
      ]
    }
  ],
  "articles": {
    "shardscript-philosophy": {
      "slug": "shardscript-philosophy",
      "title": "ShardScript Philosophy",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 1,
      "file": "getting-started/01-philosophy.mdx",
      "section": "getting-started"
    },
    "runtime-architecture": {
      "slug": "runtime-architecture",
      "title": "Runtime Architecture",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 2,
      "file": "getting-started/02-runtime-architecture.mdx",
      "section": "getting-started"
    },
    "installation-and-setup": {
      "slug": "installation-and-setup",
      "title": "Installation & Setup",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 3,
      "file": "getting-started/03-installation-and-setup.mdx",
      "section": "getting-started"
    },
    "variables-and-types": {
      "slug": "variables-and-types",
      "title": "Variables and Types",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 1,
      "file": "syntax/fundamentals/01-variables-and-types.mdx",
      "section": "syntax"
    },
    "type-inference": {
      "slug": "type-inference",
      "title": "Type Inference",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 2,
      "file": "syntax/fundamentals/02-type-inference.mdx",
      "section": "syntax"
    },
    "primitive-types": {
      "slug": "primitive-types",
      "title": "Primitive Types",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 3,
      "file": "syntax/fundamentals/03-primitive-types.mdx",
      "section": "syntax"
    },
    "operators": {
      "slug": "operators",
      "title": "Operators",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 5,
      "file": "syntax/fundamentals/04-operators.mdx",
      "section": "syntax"
    },
    "strings-and-interpolation": {
      "slug": "strings-and-interpolation",
      "title": "Strings and Interpolation",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 6,
      "file": "syntax/fundamentals/05-strings-and-interpolation.mdx",
      "section": "syntax"
    },
    "arrays": {
      "slug": "arrays",
      "title": "Arrays",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 7,
      "file": "syntax/fundamentals/06-arrays.mdx",
      "section": "syntax"
    },
    "lists-and-dictionaries": {
      "slug": "lists-and-dictionaries",
      "title": "Lists and Dictionaries",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 8,
      "file": "syntax/fundamentals/07-lists-and-dictionaries.mdx",
      "section": "syntax"
    },
    "enums": {
      "slug": "enums",
      "title": "Enums",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 4,
      "file": "syntax/fundamentals/04-enums.mdx",
      "section": "syntax"
    },
    "conditionals": {
      "slug": "conditionals",
      "title": "Conditionals",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 1,
      "file": "syntax/control-flow/01-conditionals.mdx",
      "section": "syntax"
    },
    "loops": {
      "slug": "loops",
      "title": "Loops",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 2,
      "file": "syntax/control-flow/02-loops.mdx",
      "section": "syntax"
    },
    "switch-expressions": {
      "slug": "switch-expressions",
      "title": "switch Expressions",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 3,
      "file": "syntax/control-flow/03-switch-expressions.mdx",
      "section": "syntax"
    },
    "exceptions": {
      "slug": "exceptions",
      "title": "Exceptions and Error Handling",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 4,
      "file": "syntax/control-flow/04-exceptions.mdx",
      "section": "syntax"
    },
    "deferred-execution": {
      "slug": "deferred-execution",
      "title": "Deferred Execution",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 5,
      "file": "syntax/control-flow/05-deferred-execution.mdx",
      "section": "syntax"
    },
    "classes": {
      "slug": "classes",
      "title": "Classes",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 1,
      "file": "syntax/object-oriented/01-classes.mdx",
      "section": "syntax"
    },
    "fields-and-properties": {
      "slug": "fields-and-properties",
      "title": "Fields and Properties",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 2,
      "file": "syntax/object-oriented/02-fields-and-properties.mdx",
      "section": "syntax"
    },
    "methods": {
      "slug": "methods",
      "title": "Methods",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 3,
      "file": "syntax/object-oriented/03-methods.mdx",
      "section": "syntax"
    },
    "constructors": {
      "slug": "constructors",
      "title": "Constructors and Initialization",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 4,
      "file": "syntax/object-oriented/04-constructors.mdx",
      "section": "syntax"
    },
    "interfaces": {
      "slug": "interfaces",
      "title": "Interfaces and Abstractions",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 5,
      "file": "syntax/object-oriented/05-interfaces.mdx",
      "section": "syntax"
    },
    "extension-methods": {
      "slug": "extension-methods",
      "title": "Extension Methods",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 6,
      "file": "syntax/object-oriented/06-extension-methods.mdx",
      "section": "syntax"
    },
    "generics": {
      "slug": "generics",
      "title": "Generic Types",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 7,
      "file": "syntax/object-oriented/07-generics.mdx",
      "section": "syntax"
    },
    "operator-overloading": {
      "slug": "operator-overloading",
      "title": "Operator Overloading",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 8,
      "file": "syntax/object-oriented/08-operator-overloading.mdx",
      "section": "syntax"
    },
    "lambda-expressions": {
      "slug": "lambda-expressions",
      "title": "Lambda Expressions",
      "group": "Functional Programming",
      "groupOrder": 4,
      "order": 2,
      "file": "syntax/functional/02-lambda-expressions.mdx",
      "section": "syntax"
    },
    "closures": {
      "slug": "closures",
      "title": "Closures",
      "group": "Functional Programming",
      "groupOrder": 4,
      "order": 3,
      "file": "syntax/functional/03-closures.mdx",
      "section": "syntax"
    },
    "functions-and-delegates": {
      "slug": "functions-and-delegates",
      "title": "Functions and Delegates",
      "group": "Functional Programming",
      "groupOrder": 4,
      "order": 1,
      "file": "syntax/functional/01-functions-and-delegates.mdx",
      "section": "syntax"
    },
    "garbage-collection": {
      "slug": "garbage-collection",
      "title": "Automatic Memory Management",
      "group": "Resource Management",
      "groupOrder": 5,
      "order": 1,
      "file": "syntax/resource-management/01-garbage-collection.mdx",
      "section": "syntax"
    },
    "idisposable": {
      "slug": "idisposable",
      "title": "Deterministic Disposal",
      "group": "Resource Management",
      "groupOrder": 5,
      "order": 2,
      "file": "syntax/resource-management/02-idisposable.mdx",
      "section": "syntax"
    },
    "cooperative-multitasking": {
      "slug": "cooperative-multitasking",
      "title": "Cooperative Multitasking",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 1,
      "file": "syntax/async/01-cooperative-multitasking.mdx",
      "section": "syntax"
    },
    "async-functions": {
      "slug": "async-functions",
      "title": "Async Functions",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 2,
      "file": "syntax/async/02-async-functions.mdx",
      "section": "syntax"
    },
    "await-and-state-machines": {
      "slug": "await-and-state-machines",
      "title": "Await and State Machines",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 3,
      "file": "syntax/async/03-await-and-state-machines.mdx",
      "section": "syntax"
    },
    "task-and-valuetask": {
      "slug": "task-and-valuetask",
      "title": "Task and ValueTask",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 4,
      "file": "syntax/async/04-task-and-valuetask.mdx",
      "section": "syntax"
    },
    "cancellation-tokens": {
      "slug": "cancellation-tokens",
      "title": "Cancellation Tokens",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 5,
      "file": "syntax/async/05-cancellation-tokens.mdx",
      "section": "syntax"
    },
    "basic-math": {
      "slug": "basic-math",
      "title": "Basic Math",
      "group": "SHARD.MATH",
      "groupOrder": 1,
      "order": 1,
      "file": "stdlib/math/01-basic-math.mdx",
      "section": "stdlib"
    },
    "random-number-generation": {
      "slug": "random-number-generation",
      "title": "Random Number Generation",
      "group": "SHARD.MATH",
      "groupOrder": 1,
      "order": 3,
      "file": "stdlib/math/02-random.mdx",
      "section": "stdlib"
    },
    "trigonometry-and-logarithms": {
      "slug": "trigonometry-and-logarithms",
      "title": "Trigonometry & Logarithms",
      "group": "SHARD.MATH",
      "groupOrder": 1,
      "order": 2,
      "file": "stdlib/math/02-trigonometry-and-logarithms.mdx",
      "section": "stdlib"
    },
    "environment": {
      "slug": "environment",
      "title": "Environment",
      "group": "SHARD.ENVIRONMENT",
      "groupOrder": 2,
      "order": 1,
      "file": "stdlib/environment/environment.mdx",
      "section": "stdlib"
    },
    "developer-tools": {
      "slug": "developer-tools",
      "title": "Developer Tools",
      "group": "SHARD.DEBUG",
      "groupOrder": 3,
      "order": 1,
      "file": "stdlib/debug/developer-tools.mdx",
      "section": "stdlib"
    },
    "vm-inspection": {
      "slug": "vm-inspection",
      "title": "VM Inspection",
      "group": "SHARD.DEBUG",
      "groupOrder": 3,
      "order": 2,
      "file": "stdlib/debug/vm-inspection.mdx",
      "section": "stdlib"
    },
    "ienumerable-and-ienumerator": {
      "slug": "ienumerable-and-ienumerator",
      "title": "IEnumerable & IEnumerator",
      "group": "SHARD.COLLECTIONS",
      "groupOrder": 4,
      "order": 1,
      "file": "stdlib/collections/ienumerable-and-ienumerator.mdx",
      "section": "stdlib"
    },
    "list": {
      "slug": "list",
      "title": "List<T>",
      "group": "SHARD.COLLECTIONS",
      "groupOrder": 4,
      "order": 2,
      "file": "stdlib/collections/list.mdx",
      "section": "stdlib"
    },
    "dictionary": {
      "slug": "dictionary",
      "title": "Dictionary<K, V>",
      "group": "SHARD.COLLECTIONS",
      "groupOrder": 4,
      "order": 3,
      "file": "stdlib/collections/dictionary.mdx",
      "section": "stdlib"
    },
    "queue-and-stack": {
      "slug": "queue-and-stack",
      "title": "Queue and Stack",
      "group": "SHARD.COLLECTIONS",
      "groupOrder": 4,
      "order": 4,
      "file": "stdlib/collections/queue-and-stack.mdx",
      "section": "stdlib"
    },
    "json-serializer": {
      "slug": "json-serializer",
      "title": "JsonSerializer",
      "group": "SHARD.JSON",
      "groupOrder": 5,
      "order": 1,
      "file": "stdlib/json/json-serializer.mdx",
      "section": "stdlib"
    },
    "json-node": {
      "slug": "json-node",
      "title": "JsonNode",
      "group": "SHARD.JSON",
      "groupOrder": 5,
      "order": 2,
      "file": "stdlib/json/json-node.mdx",
      "section": "stdlib"
    },
    "stream-interfaces": {
      "slug": "stream-interfaces",
      "title": "Stream Interfaces",
      "group": "SHARD.STREAMS",
      "groupOrder": 6,
      "order": 1,
      "file": "stdlib/streams/stream-interfaces.mdx",
      "section": "stdlib"
    },
    "memory-stream": {
      "slug": "memory-stream",
      "title": "MemoryStream",
      "group": "SHARD.STREAMS",
      "groupOrder": 6,
      "order": 2,
      "file": "stdlib/streams/memory-stream.mdx",
      "section": "stdlib"
    },
    "stream-reader-writer": {
      "slug": "stream-reader-writer",
      "title": "StreamReader / StreamWriter",
      "group": "SHARD.STREAMS",
      "groupOrder": 6,
      "order": 3,
      "file": "stdlib/streams/stream-reader-writer.mdx",
      "section": "stdlib"
    },
    "binary-reader-writer": {
      "slug": "binary-reader-writer",
      "title": "BinaryReader / BinaryWriter",
      "group": "SHARD.STREAMS",
      "groupOrder": 6,
      "order": 4,
      "file": "stdlib/streams/binary-reader-writer.mdx",
      "section": "stdlib"
    },
    "file-and-path": {
      "slug": "file-and-path",
      "title": "File & Path",
      "group": "SHARD.FILESYSTEM",
      "groupOrder": 7,
      "order": 1,
      "file": "stdlib/filesystem/file-and-path.mdx",
      "section": "stdlib"
    },
    "directory-and-directoryinfo": {
      "slug": "directory-and-directoryinfo",
      "title": "Directory & DirectoryInfo",
      "group": "SHARD.FILESYSTEM",
      "groupOrder": 7,
      "order": 2,
      "file": "stdlib/filesystem/directory-and-directoryinfo.mdx",
      "section": "stdlib"
    },
    "path-concatenation": {
      "slug": "path-concatenation",
      "title": "Path Concatenation",
      "group": "SHARD.FILESYSTEM",
      "groupOrder": 7,
      "order": 3,
      "file": "stdlib/filesystem/path-concatenation.mdx",
      "section": "stdlib"
    },
    "process-and-processstartinfo": {
      "slug": "process-and-processstartinfo",
      "title": "Process & ProcessStartInfo",
      "group": "SHARD.SUBPROCESS",
      "groupOrder": 8,
      "order": 1,
      "file": "stdlib/subprocess/process-and-processstartinfo.mdx",
      "section": "stdlib"
    },
    "subprocess-io-and-lifecycle": {
      "slug": "subprocess-io-and-lifecycle",
      "title": "I/O & Lifecycle",
      "group": "SHARD.SUBPROCESS",
      "groupOrder": 8,
      "order": 2,
      "file": "stdlib/subprocess/subprocess-io-and-lifecycle.mdx",
      "section": "stdlib"
    },
    "task-completion-source": {
      "slug": "task-completion-source",
      "title": "TaskCompletionSource<T>",
      "group": "SHARD.ASYNC",
      "groupOrder": 9,
      "order": 1,
      "file": "stdlib/async/task-completion-source.mdx",
      "section": "stdlib"
    },
    "cancellation-token-and-source": {
      "slug": "cancellation-token-and-source",
      "title": "CancellationToken & CancellationTokenSource",
      "group": "SHARD.ASYNC",
      "groupOrder": 9,
      "order": 2,
      "file": "stdlib/async/cancellation-token-and-source.mdx",
      "section": "stdlib"
    },
    "native-interop": {
      "slug": "native-interop",
      "title": "Native Interop",
      "group": "SHARD.INTEROP",
      "groupOrder": 10,
      "order": 1,
      "file": "stdlib/interop/native-interop.mdx",
      "section": "stdlib"
    },
    "http-client": {
      "slug": "http-client",
      "title": "HttpClient",
      "group": "SHARD.HTTP",
      "groupOrder": 11,
      "order": 1,
      "file": "stdlib/http/http-client.mdx",
      "section": "stdlib"
    },
    "http-server": {
      "slug": "http-server",
      "title": "HttpServer",
      "group": "SHARD.HTTP",
      "groupOrder": 11,
      "order": 2,
      "file": "stdlib/http/http-server.mdx",
      "section": "stdlib"
    },
    "tcp-sockets": {
      "slug": "tcp-sockets",
      "title": "TCP Sockets",
      "group": "SHARD.SOCKET",
      "groupOrder": 12,
      "order": 1,
      "file": "stdlib/socket/tcp-sockets.mdx",
      "section": "stdlib"
    },
    "type-introspection": {
      "slug": "type-introspection",
      "title": "Type Introspection",
      "group": "SHARD.REFLECTION",
      "groupOrder": 13,
      "order": 1,
      "file": "stdlib/reflection/type-introspection.mdx",
      "section": "stdlib"
    },
    "callback-contract-overview": {
      "slug": "callback-contract-overview",
      "title": "The Native Callback Contract",
      "group": "Runtime Callback Contract",
      "groupOrder": 4,
      "order": 1,
      "file": "library-building/callback-contract-overview.mdx",
      "section": "library-building"
    },
    "interface-symbol-builder": {
      "slug": "interface-symbol-builder",
      "title": "InterfaceSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 4,
      "file": "library-building/interface-symbol-builder.mdx",
      "section": "library-building"
    },
    "operator-symbol-builder": {
      "slug": "operator-symbol-builder",
      "title": "OperatorSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 10,
      "file": "library-building/operator-symbol-builder.mdx",
      "section": "library-building"
    },
    "accessibility-and-linking": {
      "slug": "accessibility-and-linking",
      "title": "Accessibility & Linking Values",
      "group": "Core API & Entry Point",
      "groupOrder": 2,
      "order": 3,
      "file": "library-building/accessibility-and-linking.mdx",
      "section": "library-building"
    },
    "async-await-native": {
      "slug": "async-await-native",
      "title": "Async / Await in Native Libraries",
      "group": "Advanced Topics",
      "groupOrder": 5,
      "order": 2,
      "file": "library-building/async-await-native.mdx",
      "section": "library-building"
    },
    "class-symbol-builder": {
      "slug": "class-symbol-builder",
      "title": "ClassSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 2,
      "file": "library-building/class-symbol-builder.mdx",
      "section": "library-building"
    },
    "constructor-symbol-builder": {
      "slug": "constructor-symbol-builder",
      "title": "ConstructorSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 7,
      "file": "library-building/constructor-symbol-builder.mdx",
      "section": "library-building"
    },
    "design-best-practices": {
      "slug": "design-best-practices",
      "title": "Design Best Practices",
      "group": "Best Practices & Troubleshooting",
      "groupOrder": 6,
      "order": 1,
      "file": "library-building/design-best-practices.mdx",
      "section": "library-building"
    },
    "enum-symbol-builder": {
      "slug": "enum-symbol-builder",
      "title": "EnumSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 5,
      "file": "library-building/enum-symbol-builder.mdx",
      "section": "library-building"
    },
    "example-async-io": {
      "slug": "example-async-io",
      "title": "Example: File/Stream I/O",
      "group": "Example Projects & Patterns",
      "groupOrder": 7,
      "order": 3,
      "file": "library-building/example-async-io.mdx",
      "section": "library-building"
    },
    "example-generic-collections": {
      "slug": "example-generic-collections",
      "title": "Example: shard.collections",
      "group": "Example Projects & Patterns",
      "groupOrder": 7,
      "order": 2,
      "file": "library-building/example-generic-collections.mdx",
      "section": "library-building"
    },
    "example-math-library": {
      "slug": "example-math-library",
      "title": "Example: shard.math",
      "group": "Example Projects & Patterns",
      "groupOrder": 7,
      "order": 1,
      "file": "library-building/example-math-library.mdx",
      "section": "library-building"
    },
    "example-native-handle-wrapper": {
      "slug": "example-native-handle-wrapper",
      "title": "Example: Wrapping a C++ Class with nint & IDisposable",
      "group": "Example Projects & Patterns",
      "groupOrder": 7,
      "order": 4,
      "file": "library-building/example-native-handle-wrapper.mdx",
      "section": "library-building"
    },
    "garbage-collection-rules": {
      "slug": "garbage-collection-rules",
      "title": "Garbage Collection Rules",
      "group": "Runtime Callback Contract",
      "groupOrder": 4,
      "order": 7,
      "file": "library-building/garbage-collection-rules.mdx",
      "section": "library-building"
    },
    "generic-types-and-type-parameters": {
      "slug": "generic-types-and-type-parameters",
      "title": "Generic Types & Type Parameters",
      "group": "Advanced Topics",
      "groupOrder": 5,
      "order": 1,
      "file": "library-building/generic-types-and-type-parameters.mdx",
      "section": "library-building"
    },
    "headers-quick-reference": {
      "slug": "headers-quick-reference",
      "title": "Header Reference",
      "group": "Core API & Entry Point",
      "groupOrder": 2,
      "order": 2,
      "file": "library-building/headers-quick-reference.mdx",
      "section": "library-building"
    },
    "indexer-symbol-builder": {
      "slug": "indexer-symbol-builder",
      "title": "IndexatorSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 9,
      "file": "library-building/indexer-symbol-builder.mdx",
      "section": "library-building"
    },
    "inter-library-dependencies": {
      "slug": "inter-library-dependencies",
      "title": "Inter-Library Dependencies",
      "group": "Advanced Topics",
      "groupOrder": 5,
      "order": 3,
      "file": "library-building/inter-library-dependencies.mdx",
      "section": "library-building"
    },
    "library-build-setup": {
      "slug": "library-build-setup",
      "title": "Build Setup & CMake Integration",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 3,
      "file": "library-building/library-build-setup.mdx",
      "section": "library-building"
    },
    "method-symbol-builder": {
      "slug": "method-symbol-builder",
      "title": "MethodSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 6,
      "file": "library-building/method-symbol-builder.mdx",
      "section": "library-building"
    },
    "namespace-symbol-builder": {
      "slug": "namespace-symbol-builder",
      "title": "NamespaceSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 1,
      "file": "library-building/namespace-symbol-builder.mdx",
      "section": "library-building"
    },
    "native-handles-and-object-lifetime": {
      "slug": "native-handles-and-object-lifetime",
      "title": "Native Handles, nint & Object Lifetime",
      "group": "Advanced Topics",
      "groupOrder": 5,
      "order": 5,
      "file": "library-building/native-handles-and-object-lifetime.mdx",
      "section": "library-building"
    },
    "native-library-overview": {
      "slug": "native-library-overview",
      "title": "Native Libraries Overview",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 1,
      "file": "library-building/native-library-overview.mdx",
      "section": "library-building"
    },
    "property-symbol-builder": {
      "slug": "property-symbol-builder",
      "title": "PropertySymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 8,
      "file": "library-building/property-symbol-builder.mdx",
      "section": "library-building"
    },
    "reading-arguments": {
      "slug": "reading-arguments",
      "title": "Reading Arguments",
      "group": "Runtime Callback Contract",
      "groupOrder": 4,
      "order": 2,
      "file": "library-building/reading-arguments.mdx",
      "section": "library-building"
    },
    "reflection-style-lookups": {
      "slug": "reflection-style-lookups",
      "title": "Reflection-Style Lookups",
      "group": "Advanced Topics",
      "groupOrder": 5,
      "order": 4,
      "file": "library-building/reflection-style-lookups.mdx",
      "section": "library-building"
    },
    "returning-values": {
      "slug": "returning-values",
      "title": "Returning Values",
      "group": "Runtime Callback Contract",
      "groupOrder": 4,
      "order": 3,
      "file": "library-building/returning-values.mdx",
      "section": "library-building"
    },
    "shardlib-entrypoint": {
      "slug": "shardlib-entrypoint",
      "title": "SHARDLIB_GETMETADATA & SHARDLIB_ENTRYPOINT",
      "group": "Core API & Entry Point",
      "groupOrder": 2,
      "order": 1,
      "file": "library-building/shardlib-entrypoint.mdx",
      "section": "library-building"
    },
    "struct-symbol-builder": {
      "slug": "struct-symbol-builder",
      "title": "StructSymbol Builder",
      "group": "SymbolBuilder Types",
      "groupOrder": 3,
      "order": 3,
      "file": "library-building/struct-symbol-builder.mdx",
      "section": "library-building"
    },
    "troubleshooting": {
      "slug": "troubleshooting",
      "title": "Common Problems & Solutions",
      "group": "Best Practices & Troubleshooting",
      "groupOrder": 6,
      "order": 2,
      "file": "library-building/troubleshooting.mdx",
      "section": "library-building"
    },
    "working-with-arrays": {
      "slug": "working-with-arrays",
      "title": "Working with Arrays",
      "group": "Runtime Callback Contract",
      "groupOrder": 4,
      "order": 6,
      "file": "library-building/working-with-arrays.mdx",
      "section": "library-building"
    },
    "working-with-fields": {
      "slug": "working-with-fields",
      "title": "Working with Fields",
      "group": "Runtime Callback Contract",
      "groupOrder": 4,
      "order": 5,
      "file": "library-building/working-with-fields.mdx",
      "section": "library-building"
    },
    "working-with-objects": {
      "slug": "working-with-objects",
      "title": "Working with Objects",
      "group": "Runtime Callback Contract",
      "groupOrder": 4,
      "order": 4,
      "file": "library-building/working-with-objects.mdx",
      "section": "library-building"
    },
    "your-first-shard-cpp-library": {
      "slug": "your-first-shard-cpp-library",
      "title": "Your First Native Library",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 2,
      "file": "library-building/your-first-shard-cpp-library.mdx",
      "section": "library-building"
    },
    "example-http-client-server": {
      "slug": "example-http-client-server",
      "title": "Example: HTTP Client/Server",
      "group": "Example Projects & Patterns",
      "groupOrder": 7,
      "order": 5,
      "file": "library-building/example-http-client-server.mdx",
      "section": "library-building"
    },
    "native-callback-helpers": {
      "slug": "native-callback-helpers",
      "title": "Native Callback Helpers",
      "group": "Runtime Callback Contract",
      "groupOrder": 4,
      "order": 8,
      "file": "library-building/native-callback-helpers.mdx",
      "section": "library-building"
    },
    "async-helpers-reference": {
      "slug": "async-helpers-reference",
      "title": "Async Helpers Reference",
      "group": "Advanced Topics",
      "groupOrder": 5,
      "order": 6,
      "file": "library-building/async-helpers-reference.mdx",
      "section": "library-building"
    },
    "native-helpers-reference": {
      "slug": "native-helpers-reference",
      "title": "Native Helpers Reference",
      "group": "Advanced Topics",
      "groupOrder": 5,
      "order": 7,
      "file": "library-building/native-helpers-reference.mdx",
      "section": "library-building"
    }
  }
}

export default manifest
