// Auto-generated by scripts/build-docs-manifest.ts
// Do not edit manually.

export type DocSection =
  | 'getting-started'
  | 'language-overview'
  | 'language-fundamentals'
  | 'language-rules'
  | 'syntax'
  | 'stdlib'
  | 'library-building'
  | 'build-your-project'
  | 'implementation-details'
  | 'faq'
  | 'common-language-features'

export interface DocArticle {
  slug: string
  title: string
  group: string
  groupOrder: number
  order: number
  file: string
  section: DocSection
}

export interface DocGroup {
  title: string
  items: { slug: string; title: string }[]
}

export interface DocManifest {
  'getting-started': DocGroup[]
  'language-overview': DocGroup[]
  'language-fundamentals': DocGroup[]
  'language-rules': DocGroup[]
  syntax: DocGroup[]
  stdlib: DocGroup[]
  'library-building': DocGroup[]
  'build-your-project': DocGroup[]
  'implementation-details': DocGroup[]
  faq: DocGroup[]
  'common-language-features': DocGroup[]
  articles: Record<string, DocArticle>
}

const manifest: DocManifest = {
  "getting-started": [
    {
      "title": "Getting Started",
      "items": [
        {
          "slug": "shardscript-philosophy",
          "title": "ShardScript Philosophy"
        },
        {
          "slug": "installation",
          "title": "Installation"
        },
        {
          "slug": "hello-world",
          "title": "Hello World"
        },
        {
          "slug": "building-from-source",
          "title": "Building from Source"
        },
        {
          "slug": "runtime-architecture",
          "title": "Runtime Architecture"
        }
      ]
    }
  ],
  "language-overview": [
    {
      "title": "Language Overview",
      "items": [
        {
          "slug": "feature-tour",
          "title": "Feature Tour"
        },
        {
          "slug": "type-system",
          "title": "Type System"
        }
      ]
    }
  ],
  "language-fundamentals": [
    {
      "title": "Language Fundamentals",
      "items": [
        {
          "slug": "comments",
          "title": "Comments"
        },
        {
          "slug": "functions",
          "title": "Functions"
        }
      ]
    }
  ],
  "language-rules": [
    {
      "title": "Language Rules",
      "items": [
        {
          "slug": "implicit-conversions",
          "title": "Implicit Conversions"
        },
        {
          "slug": "operator-precedence",
          "title": "Operator Precedence"
        },
        {
          "slug": "runtime-exceptions",
          "title": "Runtime Exceptions"
        },
        {
          "slug": "undefined-behaviour",
          "title": "Undefined Behaviour"
        }
      ]
    }
  ],
  "syntax": [
    {
      "title": "Fundamentals",
      "items": [
        {
          "slug": "variables-and-types",
          "title": "Variables and Types"
        },
        {
          "slug": "type-inference",
          "title": "Type Inference"
        },
        {
          "slug": "primitive-types",
          "title": "Primitive Types"
        },
        {
          "slug": "enums",
          "title": "Enums"
        },
        {
          "slug": "operators",
          "title": "Operators"
        },
        {
          "slug": "strings-and-interpolation",
          "title": "Strings and Interpolation"
        },
        {
          "slug": "arrays",
          "title": "Arrays"
        },
        {
          "slug": "lists-and-dictionaries",
          "title": "Lists and Dictionaries"
        }
      ]
    },
    {
      "title": "Control Flow",
      "items": [
        {
          "slug": "conditionals",
          "title": "Conditionals"
        },
        {
          "slug": "loops",
          "title": "Loops"
        },
        {
          "slug": "switch-expressions",
          "title": "switch Expressions"
        },
        {
          "slug": "switch-statements",
          "title": "switch Statements"
        },
        {
          "slug": "exceptions",
          "title": "Exceptions and Error Handling"
        },
        {
          "slug": "deferred-execution",
          "title": "Deferred Execution"
        }
      ]
    },
    {
      "title": "Object-Oriented Programming",
      "items": [
        {
          "slug": "classes",
          "title": "Classes"
        },
        {
          "slug": "fields-and-properties",
          "title": "Fields and Properties"
        },
        {
          "slug": "methods",
          "title": "Methods"
        },
        {
          "slug": "constructors",
          "title": "Constructors and Initialization"
        },
        {
          "slug": "interfaces",
          "title": "Interfaces and Abstractions"
        },
        {
          "slug": "extension-methods",
          "title": "Extension Methods"
        },
        {
          "slug": "generics",
          "title": "Generic Types"
        },
        {
          "slug": "operator-overloading",
          "title": "Operator Overloading"
        }
      ]
    },
    {
      "title": "Functional Programming",
      "items": [
        {
          "slug": "delegates",
          "title": "Delegates"
        },
        {
          "slug": "lambda-expressions",
          "title": "Lambda Expressions"
        },
        {
          "slug": "closures",
          "title": "Closures"
        }
      ]
    },
    {
      "title": "Resource Management",
      "items": [
        {
          "slug": "garbage-collection",
          "title": "Automatic Memory Management"
        },
        {
          "slug": "object-lifetime",
          "title": "Object Lifetime"
        }
      ]
    },
    {
      "title": "Asynchronous Programming",
      "items": [
        {
          "slug": "cooperative-multitasking",
          "title": "Cooperative Multitasking"
        },
        {
          "slug": "async-functions",
          "title": "Async Functions"
        },
        {
          "slug": "await-and-state-machines",
          "title": "Await and State Machines"
        },
        {
          "slug": "task-and-valuetask",
          "title": "Task and ValueTask"
        },
        {
          "slug": "cancellation-tokens",
          "title": "Cancellation Tokens"
        }
      ]
    }
  ],
  "stdlib": [
    {
      "title": "SHARD.CONSTREAM",
      "items": [
        {
          "slug": "console-io",
          "title": "Console I/O"
        }
      ]
    },
    {
      "title": "SHARD.MATH",
      "items": [
        {
          "slug": "basic-math",
          "title": "Basic Math"
        },
        {
          "slug": "trigonometry-and-logarithms",
          "title": "Trigonometry & Logarithms"
        },
        {
          "slug": "random-number-generation",
          "title": "Random Number Generation"
        }
      ]
    },
    {
      "title": "SHARD.ENVIRONMENT",
      "items": [
        {
          "slug": "environment",
          "title": "Environment"
        }
      ]
    },
    {
      "title": "SHARD.DEBUG",
      "items": [
        {
          "slug": "developer-tools",
          "title": "Developer Tools"
        },
        {
          "slug": "vm-inspection",
          "title": "VM Inspection"
        }
      ]
    },
    {
      "title": "SHARD.COLLECTIONS",
      "items": [
        {
          "slug": "ienumerable-and-ienumerator",
          "title": "IEnumerable & IEnumerator"
        },
        {
          "slug": "list",
          "title": "List<T>"
        },
        {
          "slug": "dictionary",
          "title": "Dictionary<K, V>"
        },
        {
          "slug": "queue-and-stack",
          "title": "Queue and Stack"
        }
      ]
    },
    {
      "title": "SHARD.JSON",
      "items": [
        {
          "slug": "json-serializer",
          "title": "JsonSerializer"
        },
        {
          "slug": "json-node",
          "title": "JsonNode"
        }
      ]
    },
    {
      "title": "SHARD.STREAMS",
      "items": [
        {
          "slug": "stream-interfaces",
          "title": "Stream Interfaces"
        },
        {
          "slug": "memory-stream",
          "title": "MemoryStream"
        },
        {
          "slug": "stream-reader-writer",
          "title": "StreamReader / StreamWriter"
        },
        {
          "slug": "binary-reader-writer",
          "title": "BinaryReader / BinaryWriter"
        }
      ]
    },
    {
      "title": "SHARD.FILESYSTEM",
      "items": [
        {
          "slug": "file-and-path",
          "title": "File & Path"
        },
        {
          "slug": "directory-and-directoryinfo",
          "title": "Directory & DirectoryInfo"
        },
        {
          "slug": "path-concatenation",
          "title": "Path Concatenation"
        }
      ]
    },
    {
      "title": "SHARD.SUBPROCESS",
      "items": [
        {
          "slug": "process-and-processstartinfo",
          "title": "Process & ProcessStartInfo"
        },
        {
          "slug": "subprocess-io-and-lifecycle",
          "title": "I/O & Lifecycle"
        }
      ]
    },
    {
      "title": "SHARD.ASYNC",
      "items": [
        {
          "slug": "task-completion-source",
          "title": "TaskCompletionSource<T>"
        },
        {
          "slug": "cancellation-token-and-source",
          "title": "CancellationToken & CancellationTokenSource"
        }
      ]
    },
    {
      "title": "SHARD.INTEROP",
      "items": [
        {
          "slug": "native-interop",
          "title": "Native Interop"
        }
      ]
    },
    {
      "title": "SHARD.HTTP",
      "items": [
        {
          "slug": "http-client",
          "title": "HttpClient"
        },
        {
          "slug": "http-server",
          "title": "HttpServer"
        }
      ]
    },
    {
      "title": "SHARD.SOCKET",
      "items": [
        {
          "slug": "tcp-sockets",
          "title": "TCP Sockets"
        }
      ]
    },
    {
      "title": "SHARD.REFLECTION",
      "items": [
        {
          "slug": "type-introspection",
          "title": "Type Introspection"
        }
      ]
    },
    {
      "title": "SHARD.TIME",
      "items": [
        {
          "slug": "date-and-time",
          "title": "Date & Time"
        }
      ]
    }
  ],
  "library-building": [
    {
      "title": "Concepts",
      "items": [
        {
          "slug": "native-library-overview",
          "title": "Native Libraries Overview"
        },
        {
          "slug": "callback-contract-overview",
          "title": "The Native Callback Contract"
        },
        {
          "slug": "garbage-collection-rules",
          "title": "Garbage Collection Rules"
        },
        {
          "slug": "native-handles-and-object-lifetime",
          "title": "Native Handles, nint & Object Lifetime"
        },
        {
          "slug": "design-best-practices",
          "title": "Design Best Practices"
        }
      ]
    },
    {
      "title": "Tutorials",
      "items": [
        {
          "slug": "your-first-shard-cpp-library",
          "title": "Your First Native Library"
        },
        {
          "slug": "example-math-library",
          "title": "Example: shard.math"
        },
        {
          "slug": "example-generic-collections",
          "title": "Example: shard.collections"
        },
        {
          "slug": "example-async-io",
          "title": "Example: File/Stream I/O"
        },
        {
          "slug": "example-native-handle-wrapper",
          "title": "Example: Wrapping a C++ Class with nint & IDisposable"
        },
        {
          "slug": "example-http-client-server",
          "title": "Example: HTTP Client/Server"
        }
      ]
    },
    {
      "title": "How-To Guides",
      "items": [
        {
          "slug": "library-build-setup",
          "title": "Build Setup & CMake Integration"
        },
        {
          "slug": "reading-arguments",
          "title": "Reading Arguments"
        },
        {
          "slug": "returning-values",
          "title": "Returning Values"
        },
        {
          "slug": "working-with-objects",
          "title": "Working with Objects"
        },
        {
          "slug": "working-with-fields",
          "title": "Working with Fields"
        },
        {
          "slug": "working-with-arrays",
          "title": "Working with Arrays"
        },
        {
          "slug": "throwing-typed-exceptions",
          "title": "Throwing Typed Exceptions from Native Libraries"
        },
        {
          "slug": "generic-types-and-type-parameters",
          "title": "Generic Types & Type Parameters"
        },
        {
          "slug": "inter-library-dependencies",
          "title": "Inter-Library Dependencies"
        },
        {
          "slug": "reflection-style-lookups",
          "title": "Reflection-Style Lookups"
        },
        {
          "slug": "async-await-native",
          "title": "Async / Await in Native Libraries"
        },
        {
          "slug": "troubleshooting",
          "title": "Common Problems & Solutions"
        }
      ]
    },
    {
      "title": "Reference",
      "items": [
        {
          "slug": "shardlib-entrypoint",
          "title": "SHARDLIB_GETMETADATA & SHARDLIB_ENTRYPOINT"
        },
        {
          "slug": "headers-quick-reference",
          "title": "Header Reference"
        },
        {
          "slug": "accessibility-and-linking",
          "title": "Accessibility & Linking Values"
        },
        {
          "slug": "namespace-symbol-builder",
          "title": "NamespaceSymbol Builder"
        },
        {
          "slug": "class-symbol-builder",
          "title": "ClassSymbol Builder"
        },
        {
          "slug": "struct-symbol-builder",
          "title": "StructSymbol Builder"
        },
        {
          "slug": "interface-symbol-builder",
          "title": "InterfaceSymbol Builder"
        },
        {
          "slug": "enum-symbol-builder",
          "title": "EnumSymbol Builder"
        },
        {
          "slug": "constructor-symbol-builder",
          "title": "ConstructorSymbol Builder"
        },
        {
          "slug": "method-symbol-builder",
          "title": "MethodSymbol Builder"
        },
        {
          "slug": "property-symbol-builder",
          "title": "PropertySymbol Builder"
        },
        {
          "slug": "indexer-symbol-builder",
          "title": "IndexatorSymbol Builder"
        },
        {
          "slug": "operator-symbol-builder",
          "title": "OperatorSymbol Builder"
        },
        {
          "slug": "native-callback-helpers",
          "title": "Native Callback Helpers"
        },
        {
          "slug": "async-helpers-reference",
          "title": "Async Helpers Reference"
        },
        {
          "slug": "native-helpers-reference",
          "title": "Native Helpers Reference"
        },
        {
          "slug": "runtime-exception-reference",
          "title": "shard::runtime_exception"
        }
      ]
    }
  ],
  "build-your-project": [
    {
      "title": "Build Your Project",
      "items": [
        {
          "slug": "the-shard-cli",
          "title": "The shard CLI"
        },
        {
          "slug": "project-configuration",
          "title": "Project Configuration"
        },
        {
          "slug": "package-management-with-geode",
          "title": "Package Management with Geode"
        },
        {
          "slug": "library-search-paths",
          "title": "Library Search Paths"
        }
      ]
    }
  ],
  "implementation-details": [
    {
      "title": "Implementation Details",
      "items": [
        {
          "slug": "compiler-pipeline",
          "title": "Compiler Pipeline"
        },
        {
          "slug": "bytecode-and-opcodes",
          "title": "Bytecode and OpCodes"
        },
        {
          "slug": "virtual-machine-internals",
          "title": "Virtual Machine Internals"
        },
        {
          "slug": "event-loop-and-libuv",
          "title": "Event Loop and libuv"
        }
      ]
    }
  ],
  "faq": [
    {
      "title": "FAQ",
      "items": [
        {
          "slug": "faq",
          "title": "FAQ"
        },
        {
          "slug": "comparison-with-other-languages",
          "title": "Comparison with Other Languages"
        },
        {
          "slug": "rejected-ideas",
          "title": "Rejected Ideas"
        },
        {
          "slug": "roadmap",
          "title": "Roadmap"
        },
        {
          "slug": "design-goals",
          "title": "Design Goals"
        }
      ]
    }
  ],
  "common-language-features": [
    {
      "title": "Common Language Features",
      "items": [
        {
          "slug": "defer-and-idisposable",
          "title": "Defer and IDisposable"
        }
      ]
    }
  ],
  "articles": {
    "shardscript-philosophy": {
      "slug": "shardscript-philosophy",
      "title": "ShardScript Philosophy",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 1,
      "file": "getting-started/01-philosophy.mdx",
      "section": "getting-started"
    },
    "runtime-architecture": {
      "slug": "runtime-architecture",
      "title": "Runtime Architecture",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 5,
      "file": "getting-started/05-runtime-architecture.mdx",
      "section": "getting-started"
    },
    "installation": {
      "slug": "installation",
      "title": "Installation",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 2,
      "file": "getting-started/02-installation.mdx",
      "section": "getting-started"
    },
    "building-from-source": {
      "slug": "building-from-source",
      "title": "Building from Source",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 4,
      "file": "getting-started/04-building-from-source.mdx",
      "section": "getting-started"
    },
    "hello-world": {
      "slug": "hello-world",
      "title": "Hello World",
      "group": "Getting Started",
      "groupOrder": 1,
      "order": 3,
      "file": "getting-started/03-hello-world.mdx",
      "section": "getting-started"
    },
    "feature-tour": {
      "slug": "feature-tour",
      "title": "Feature Tour",
      "group": "Language Overview",
      "groupOrder": 2,
      "order": 1,
      "file": "language-overview/01-feature-tour.mdx",
      "section": "language-overview"
    },
    "type-system": {
      "slug": "type-system",
      "title": "Type System",
      "group": "Language Overview",
      "groupOrder": 2,
      "order": 2,
      "file": "language-overview/02-type-system.mdx",
      "section": "language-overview"
    },
    "comments": {
      "slug": "comments",
      "title": "Comments",
      "group": "Language Fundamentals",
      "groupOrder": 3,
      "order": 5,
      "file": "language-fundamentals/05-comments.mdx",
      "section": "language-fundamentals"
    },
    "functions": {
      "slug": "functions",
      "title": "Functions",
      "group": "Language Fundamentals",
      "groupOrder": 3,
      "order": 6,
      "file": "language-fundamentals/06-functions.mdx",
      "section": "language-fundamentals"
    },
    "implicit-conversions": {
      "slug": "implicit-conversions",
      "title": "Implicit Conversions",
      "group": "Language Rules",
      "groupOrder": 9,
      "order": 1,
      "file": "language-rules/01-implicit-conversions.mdx",
      "section": "language-rules"
    },
    "operator-precedence": {
      "slug": "operator-precedence",
      "title": "Operator Precedence",
      "group": "Language Rules",
      "groupOrder": 9,
      "order": 2,
      "file": "language-rules/02-operator-precedence.mdx",
      "section": "language-rules"
    },
    "runtime-exceptions": {
      "slug": "runtime-exceptions",
      "title": "Runtime Exceptions",
      "group": "Language Rules",
      "groupOrder": 9,
      "order": 3,
      "file": "language-rules/03-runtime-exceptions.mdx",
      "section": "language-rules"
    },
    "undefined-behaviour": {
      "slug": "undefined-behaviour",
      "title": "Undefined Behaviour",
      "group": "Language Rules",
      "groupOrder": 9,
      "order": 4,
      "file": "language-rules/04-undefined-behaviour.mdx",
      "section": "language-rules"
    },
    "variables-and-types": {
      "slug": "variables-and-types",
      "title": "Variables and Types",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 1,
      "file": "syntax/fundamentals/01-variables-and-types.mdx",
      "section": "syntax"
    },
    "type-inference": {
      "slug": "type-inference",
      "title": "Type Inference",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 2,
      "file": "syntax/fundamentals/02-type-inference.mdx",
      "section": "syntax"
    },
    "primitive-types": {
      "slug": "primitive-types",
      "title": "Primitive Types",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 3,
      "file": "syntax/fundamentals/03-primitive-types.mdx",
      "section": "syntax"
    },
    "operators": {
      "slug": "operators",
      "title": "Operators",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 5,
      "file": "syntax/fundamentals/04-operators.mdx",
      "section": "syntax"
    },
    "strings-and-interpolation": {
      "slug": "strings-and-interpolation",
      "title": "Strings and Interpolation",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 6,
      "file": "syntax/fundamentals/05-strings-and-interpolation.mdx",
      "section": "syntax"
    },
    "arrays": {
      "slug": "arrays",
      "title": "Arrays",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 7,
      "file": "syntax/fundamentals/06-arrays.mdx",
      "section": "syntax"
    },
    "lists-and-dictionaries": {
      "slug": "lists-and-dictionaries",
      "title": "Lists and Dictionaries",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 8,
      "file": "syntax/fundamentals/07-lists-and-dictionaries.mdx",
      "section": "syntax"
    },
    "enums": {
      "slug": "enums",
      "title": "Enums",
      "group": "Fundamentals",
      "groupOrder": 1,
      "order": 4,
      "file": "syntax/fundamentals/04-enums.mdx",
      "section": "syntax"
    },
    "conditionals": {
      "slug": "conditionals",
      "title": "Conditionals",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 1,
      "file": "syntax/control-flow/01-conditionals.mdx",
      "section": "syntax"
    },
    "loops": {
      "slug": "loops",
      "title": "Loops",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 2,
      "file": "syntax/control-flow/02-loops.mdx",
      "section": "syntax"
    },
    "switch-expressions": {
      "slug": "switch-expressions",
      "title": "switch Expressions",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 3,
      "file": "syntax/control-flow/03-switch-expressions.mdx",
      "section": "syntax"
    },
    "exceptions": {
      "slug": "exceptions",
      "title": "Exceptions and Error Handling",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 5,
      "file": "syntax/control-flow/04-exceptions.mdx",
      "section": "syntax"
    },
    "deferred-execution": {
      "slug": "deferred-execution",
      "title": "Deferred Execution",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 6,
      "file": "syntax/control-flow/05-deferred-execution.mdx",
      "section": "syntax"
    },
    "switch-statements": {
      "slug": "switch-statements",
      "title": "switch Statements",
      "group": "Control Flow",
      "groupOrder": 2,
      "order": 4,
      "file": "syntax/control-flow/04-switch-statements.mdx",
      "section": "syntax"
    },
    "classes": {
      "slug": "classes",
      "title": "Classes",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 1,
      "file": "syntax/object-oriented/01-classes.mdx",
      "section": "syntax"
    },
    "fields-and-properties": {
      "slug": "fields-and-properties",
      "title": "Fields and Properties",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 2,
      "file": "syntax/object-oriented/02-fields-and-properties.mdx",
      "section": "syntax"
    },
    "methods": {
      "slug": "methods",
      "title": "Methods",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 3,
      "file": "syntax/object-oriented/03-methods.mdx",
      "section": "syntax"
    },
    "constructors": {
      "slug": "constructors",
      "title": "Constructors and Initialization",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 4,
      "file": "syntax/object-oriented/04-constructors.mdx",
      "section": "syntax"
    },
    "interfaces": {
      "slug": "interfaces",
      "title": "Interfaces and Abstractions",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 5,
      "file": "syntax/object-oriented/05-interfaces.mdx",
      "section": "syntax"
    },
    "extension-methods": {
      "slug": "extension-methods",
      "title": "Extension Methods",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 6,
      "file": "syntax/object-oriented/06-extension-methods.mdx",
      "section": "syntax"
    },
    "generics": {
      "slug": "generics",
      "title": "Generic Types",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 7,
      "file": "syntax/object-oriented/07-generics.mdx",
      "section": "syntax"
    },
    "operator-overloading": {
      "slug": "operator-overloading",
      "title": "Operator Overloading",
      "group": "Object-Oriented Programming",
      "groupOrder": 3,
      "order": 8,
      "file": "syntax/object-oriented/08-operator-overloading.mdx",
      "section": "syntax"
    },
    "lambda-expressions": {
      "slug": "lambda-expressions",
      "title": "Lambda Expressions",
      "group": "Functional Programming",
      "groupOrder": 4,
      "order": 2,
      "file": "syntax/functional/02-lambda-expressions.mdx",
      "section": "syntax"
    },
    "closures": {
      "slug": "closures",
      "title": "Closures",
      "group": "Functional Programming",
      "groupOrder": 4,
      "order": 3,
      "file": "syntax/functional/03-closures.mdx",
      "section": "syntax"
    },
    "delegates": {
      "slug": "delegates",
      "title": "Delegates",
      "group": "Functional Programming",
      "groupOrder": 4,
      "order": 1,
      "file": "syntax/functional/01-functions-and-delegates.mdx",
      "section": "syntax"
    },
    "garbage-collection": {
      "slug": "garbage-collection",
      "title": "Automatic Memory Management",
      "group": "Resource Management",
      "groupOrder": 5,
      "order": 1,
      "file": "syntax/resource-management/01-garbage-collection.mdx",
      "section": "syntax"
    },
    "object-lifetime": {
      "slug": "object-lifetime",
      "title": "Object Lifetime",
      "group": "Resource Management",
      "groupOrder": 5,
      "order": 2,
      "file": "syntax/resource-management/02-object-lifetime.mdx",
      "section": "syntax"
    },
    "cooperative-multitasking": {
      "slug": "cooperative-multitasking",
      "title": "Cooperative Multitasking",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 1,
      "file": "syntax/async/01-cooperative-multitasking.mdx",
      "section": "syntax"
    },
    "async-functions": {
      "slug": "async-functions",
      "title": "Async Functions",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 2,
      "file": "syntax/async/02-async-functions.mdx",
      "section": "syntax"
    },
    "await-and-state-machines": {
      "slug": "await-and-state-machines",
      "title": "Await and State Machines",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 3,
      "file": "syntax/async/03-await-and-state-machines.mdx",
      "section": "syntax"
    },
    "task-and-valuetask": {
      "slug": "task-and-valuetask",
      "title": "Task and ValueTask",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 4,
      "file": "syntax/async/04-task-and-valuetask.mdx",
      "section": "syntax"
    },
    "cancellation-tokens": {
      "slug": "cancellation-tokens",
      "title": "Cancellation Tokens",
      "group": "Asynchronous Programming",
      "groupOrder": 6,
      "order": 5,
      "file": "syntax/async/05-cancellation-tokens.mdx",
      "section": "syntax"
    },
    "basic-math": {
      "slug": "basic-math",
      "title": "Basic Math",
      "group": "SHARD.MATH",
      "groupOrder": 1,
      "order": 1,
      "file": "stdlib/math/01-basic-math.mdx",
      "section": "stdlib"
    },
    "random-number-generation": {
      "slug": "random-number-generation",
      "title": "Random Number Generation",
      "group": "SHARD.MATH",
      "groupOrder": 1,
      "order": 3,
      "file": "stdlib/math/02-random.mdx",
      "section": "stdlib"
    },
    "trigonometry-and-logarithms": {
      "slug": "trigonometry-and-logarithms",
      "title": "Trigonometry & Logarithms",
      "group": "SHARD.MATH",
      "groupOrder": 1,
      "order": 2,
      "file": "stdlib/math/02-trigonometry-and-logarithms.mdx",
      "section": "stdlib"
    },
    "environment": {
      "slug": "environment",
      "title": "Environment",
      "group": "SHARD.ENVIRONMENT",
      "groupOrder": 2,
      "order": 1,
      "file": "stdlib/environment/environment.mdx",
      "section": "stdlib"
    },
    "developer-tools": {
      "slug": "developer-tools",
      "title": "Developer Tools",
      "group": "SHARD.DEBUG",
      "groupOrder": 3,
      "order": 1,
      "file": "stdlib/debug/developer-tools.mdx",
      "section": "stdlib"
    },
    "vm-inspection": {
      "slug": "vm-inspection",
      "title": "VM Inspection",
      "group": "SHARD.DEBUG",
      "groupOrder": 3,
      "order": 2,
      "file": "stdlib/debug/vm-inspection.mdx",
      "section": "stdlib"
    },
    "ienumerable-and-ienumerator": {
      "slug": "ienumerable-and-ienumerator",
      "title": "IEnumerable & IEnumerator",
      "group": "SHARD.COLLECTIONS",
      "groupOrder": 4,
      "order": 1,
      "file": "stdlib/collections/ienumerable-and-ienumerator.mdx",
      "section": "stdlib"
    },
    "list": {
      "slug": "list",
      "title": "List<T>",
      "group": "SHARD.COLLECTIONS",
      "groupOrder": 4,
      "order": 2,
      "file": "stdlib/collections/list.mdx",
      "section": "stdlib"
    },
    "dictionary": {
      "slug": "dictionary",
      "title": "Dictionary<K, V>",
      "group": "SHARD.COLLECTIONS",
      "groupOrder": 4,
      "order": 3,
      "file": "stdlib/collections/dictionary.mdx",
      "section": "stdlib"
    },
    "queue-and-stack": {
      "slug": "queue-and-stack",
      "title": "Queue and Stack",
      "group": "SHARD.COLLECTIONS",
      "groupOrder": 4,
      "order": 4,
      "file": "stdlib/collections/queue-and-stack.mdx",
      "section": "stdlib"
    },
    "json-serializer": {
      "slug": "json-serializer",
      "title": "JsonSerializer",
      "group": "SHARD.JSON",
      "groupOrder": 5,
      "order": 1,
      "file": "stdlib/json/json-serializer.mdx",
      "section": "stdlib"
    },
    "json-node": {
      "slug": "json-node",
      "title": "JsonNode",
      "group": "SHARD.JSON",
      "groupOrder": 5,
      "order": 2,
      "file": "stdlib/json/json-node.mdx",
      "section": "stdlib"
    },
    "stream-interfaces": {
      "slug": "stream-interfaces",
      "title": "Stream Interfaces",
      "group": "SHARD.STREAMS",
      "groupOrder": 6,
      "order": 1,
      "file": "stdlib/streams/stream-interfaces.mdx",
      "section": "stdlib"
    },
    "memory-stream": {
      "slug": "memory-stream",
      "title": "MemoryStream",
      "group": "SHARD.STREAMS",
      "groupOrder": 6,
      "order": 2,
      "file": "stdlib/streams/memory-stream.mdx",
      "section": "stdlib"
    },
    "stream-reader-writer": {
      "slug": "stream-reader-writer",
      "title": "StreamReader / StreamWriter",
      "group": "SHARD.STREAMS",
      "groupOrder": 6,
      "order": 3,
      "file": "stdlib/streams/stream-reader-writer.mdx",
      "section": "stdlib"
    },
    "binary-reader-writer": {
      "slug": "binary-reader-writer",
      "title": "BinaryReader / BinaryWriter",
      "group": "SHARD.STREAMS",
      "groupOrder": 6,
      "order": 4,
      "file": "stdlib/streams/binary-reader-writer.mdx",
      "section": "stdlib"
    },
    "file-and-path": {
      "slug": "file-and-path",
      "title": "File & Path",
      "group": "SHARD.FILESYSTEM",
      "groupOrder": 7,
      "order": 1,
      "file": "stdlib/filesystem/file-and-path.mdx",
      "section": "stdlib"
    },
    "directory-and-directoryinfo": {
      "slug": "directory-and-directoryinfo",
      "title": "Directory & DirectoryInfo",
      "group": "SHARD.FILESYSTEM",
      "groupOrder": 7,
      "order": 2,
      "file": "stdlib/filesystem/directory-and-directoryinfo.mdx",
      "section": "stdlib"
    },
    "path-concatenation": {
      "slug": "path-concatenation",
      "title": "Path Concatenation",
      "group": "SHARD.FILESYSTEM",
      "groupOrder": 7,
      "order": 3,
      "file": "stdlib/filesystem/path-concatenation.mdx",
      "section": "stdlib"
    },
    "process-and-processstartinfo": {
      "slug": "process-and-processstartinfo",
      "title": "Process & ProcessStartInfo",
      "group": "SHARD.SUBPROCESS",
      "groupOrder": 8,
      "order": 1,
      "file": "stdlib/subprocess/process-and-processstartinfo.mdx",
      "section": "stdlib"
    },
    "subprocess-io-and-lifecycle": {
      "slug": "subprocess-io-and-lifecycle",
      "title": "I/O & Lifecycle",
      "group": "SHARD.SUBPROCESS",
      "groupOrder": 8,
      "order": 2,
      "file": "stdlib/subprocess/subprocess-io-and-lifecycle.mdx",
      "section": "stdlib"
    },
    "task-completion-source": {
      "slug": "task-completion-source",
      "title": "TaskCompletionSource<T>",
      "group": "SHARD.ASYNC",
      "groupOrder": 9,
      "order": 1,
      "file": "stdlib/async/task-completion-source.mdx",
      "section": "stdlib"
    },
    "cancellation-token-and-source": {
      "slug": "cancellation-token-and-source",
      "title": "CancellationToken & CancellationTokenSource",
      "group": "SHARD.ASYNC",
      "groupOrder": 9,
      "order": 2,
      "file": "stdlib/async/cancellation-token-and-source.mdx",
      "section": "stdlib"
    },
    "native-interop": {
      "slug": "native-interop",
      "title": "Native Interop",
      "group": "SHARD.INTEROP",
      "groupOrder": 10,
      "order": 1,
      "file": "stdlib/interop/native-interop.mdx",
      "section": "stdlib"
    },
    "http-client": {
      "slug": "http-client",
      "title": "HttpClient",
      "group": "SHARD.HTTP",
      "groupOrder": 11,
      "order": 1,
      "file": "stdlib/http/http-client.mdx",
      "section": "stdlib"
    },
    "http-server": {
      "slug": "http-server",
      "title": "HttpServer",
      "group": "SHARD.HTTP",
      "groupOrder": 11,
      "order": 2,
      "file": "stdlib/http/http-server.mdx",
      "section": "stdlib"
    },
    "tcp-sockets": {
      "slug": "tcp-sockets",
      "title": "TCP Sockets",
      "group": "SHARD.SOCKET",
      "groupOrder": 12,
      "order": 1,
      "file": "stdlib/socket/tcp-sockets.mdx",
      "section": "stdlib"
    },
    "type-introspection": {
      "slug": "type-introspection",
      "title": "Type Introspection",
      "group": "SHARD.REFLECTION",
      "groupOrder": 13,
      "order": 1,
      "file": "stdlib/reflection/type-introspection.mdx",
      "section": "stdlib"
    },
    "date-and-time": {
      "slug": "date-and-time",
      "title": "Date & Time",
      "group": "SHARD.TIME",
      "groupOrder": 14,
      "order": 1,
      "file": "stdlib/time/date-and-time.mdx",
      "section": "stdlib"
    },
    "console-io": {
      "slug": "console-io",
      "title": "Console I/O",
      "group": "SHARD.CONSTREAM",
      "groupOrder": 0,
      "order": 1,
      "file": "stdlib/constream/console-io.mdx",
      "section": "stdlib"
    },
    "native-library-overview": {
      "slug": "native-library-overview",
      "title": "Native Libraries Overview",
      "group": "Concepts",
      "groupOrder": 1,
      "order": 1,
      "file": "library-building/concepts/native-library-overview.mdx",
      "section": "library-building"
    },
    "callback-contract-overview": {
      "slug": "callback-contract-overview",
      "title": "The Native Callback Contract",
      "group": "Concepts",
      "groupOrder": 1,
      "order": 2,
      "file": "library-building/concepts/callback-contract-overview.mdx",
      "section": "library-building"
    },
    "garbage-collection-rules": {
      "slug": "garbage-collection-rules",
      "title": "Garbage Collection Rules",
      "group": "Concepts",
      "groupOrder": 1,
      "order": 3,
      "file": "library-building/concepts/garbage-collection-rules.mdx",
      "section": "library-building"
    },
    "native-handles-and-object-lifetime": {
      "slug": "native-handles-and-object-lifetime",
      "title": "Native Handles, nint & Object Lifetime",
      "group": "Concepts",
      "groupOrder": 1,
      "order": 4,
      "file": "library-building/concepts/native-handles-and-object-lifetime.mdx",
      "section": "library-building"
    },
    "design-best-practices": {
      "slug": "design-best-practices",
      "title": "Design Best Practices",
      "group": "Concepts",
      "groupOrder": 1,
      "order": 5,
      "file": "library-building/concepts/design-best-practices.mdx",
      "section": "library-building"
    },
    "your-first-shard-cpp-library": {
      "slug": "your-first-shard-cpp-library",
      "title": "Your First Native Library",
      "group": "Tutorials",
      "groupOrder": 2,
      "order": 1,
      "file": "library-building/tutorials/your-first-shard-cpp-library.mdx",
      "section": "library-building"
    },
    "example-math-library": {
      "slug": "example-math-library",
      "title": "Example: shard.math",
      "group": "Tutorials",
      "groupOrder": 2,
      "order": 2,
      "file": "library-building/tutorials/example-math-library.mdx",
      "section": "library-building"
    },
    "example-generic-collections": {
      "slug": "example-generic-collections",
      "title": "Example: shard.collections",
      "group": "Tutorials",
      "groupOrder": 2,
      "order": 3,
      "file": "library-building/tutorials/example-generic-collections.mdx",
      "section": "library-building"
    },
    "example-async-io": {
      "slug": "example-async-io",
      "title": "Example: File/Stream I/O",
      "group": "Tutorials",
      "groupOrder": 2,
      "order": 4,
      "file": "library-building/tutorials/example-async-io.mdx",
      "section": "library-building"
    },
    "example-native-handle-wrapper": {
      "slug": "example-native-handle-wrapper",
      "title": "Example: Wrapping a C++ Class with nint & IDisposable",
      "group": "Tutorials",
      "groupOrder": 2,
      "order": 5,
      "file": "library-building/tutorials/example-native-handle-wrapper.mdx",
      "section": "library-building"
    },
    "example-http-client-server": {
      "slug": "example-http-client-server",
      "title": "Example: HTTP Client/Server",
      "group": "Tutorials",
      "groupOrder": 2,
      "order": 6,
      "file": "library-building/tutorials/example-http-client-server.mdx",
      "section": "library-building"
    },
    "library-build-setup": {
      "slug": "library-build-setup",
      "title": "Build Setup & CMake Integration",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 1,
      "file": "library-building/how-to/library-build-setup.mdx",
      "section": "library-building"
    },
    "reading-arguments": {
      "slug": "reading-arguments",
      "title": "Reading Arguments",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 2,
      "file": "library-building/how-to/reading-arguments.mdx",
      "section": "library-building"
    },
    "returning-values": {
      "slug": "returning-values",
      "title": "Returning Values",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 3,
      "file": "library-building/how-to/returning-values.mdx",
      "section": "library-building"
    },
    "working-with-objects": {
      "slug": "working-with-objects",
      "title": "Working with Objects",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 4,
      "file": "library-building/how-to/working-with-objects.mdx",
      "section": "library-building"
    },
    "working-with-fields": {
      "slug": "working-with-fields",
      "title": "Working with Fields",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 5,
      "file": "library-building/how-to/working-with-fields.mdx",
      "section": "library-building"
    },
    "working-with-arrays": {
      "slug": "working-with-arrays",
      "title": "Working with Arrays",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 6,
      "file": "library-building/how-to/working-with-arrays.mdx",
      "section": "library-building"
    },
    "throwing-typed-exceptions": {
      "slug": "throwing-typed-exceptions",
      "title": "Throwing Typed Exceptions from Native Libraries",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 7,
      "file": "library-building/how-to/throwing-typed-exceptions.mdx",
      "section": "library-building"
    },
    "generic-types-and-type-parameters": {
      "slug": "generic-types-and-type-parameters",
      "title": "Generic Types & Type Parameters",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 8,
      "file": "library-building/how-to/generic-types-and-type-parameters.mdx",
      "section": "library-building"
    },
    "inter-library-dependencies": {
      "slug": "inter-library-dependencies",
      "title": "Inter-Library Dependencies",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 9,
      "file": "library-building/how-to/inter-library-dependencies.mdx",
      "section": "library-building"
    },
    "reflection-style-lookups": {
      "slug": "reflection-style-lookups",
      "title": "Reflection-Style Lookups",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 10,
      "file": "library-building/how-to/reflection-style-lookups.mdx",
      "section": "library-building"
    },
    "async-await-native": {
      "slug": "async-await-native",
      "title": "Async / Await in Native Libraries",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 11,
      "file": "library-building/how-to/async-await-native.mdx",
      "section": "library-building"
    },
    "troubleshooting": {
      "slug": "troubleshooting",
      "title": "Common Problems & Solutions",
      "group": "How-To Guides",
      "groupOrder": 3,
      "order": 12,
      "file": "library-building/how-to/troubleshooting.mdx",
      "section": "library-building"
    },
    "shardlib-entrypoint": {
      "slug": "shardlib-entrypoint",
      "title": "SHARDLIB_GETMETADATA & SHARDLIB_ENTRYPOINT",
      "group": "Reference",
      "groupOrder": 4,
      "order": 1,
      "file": "library-building/reference/shardlib-entrypoint.mdx",
      "section": "library-building"
    },
    "headers-quick-reference": {
      "slug": "headers-quick-reference",
      "title": "Header Reference",
      "group": "Reference",
      "groupOrder": 4,
      "order": 2,
      "file": "library-building/reference/headers-quick-reference.mdx",
      "section": "library-building"
    },
    "accessibility-and-linking": {
      "slug": "accessibility-and-linking",
      "title": "Accessibility & Linking Values",
      "group": "Reference",
      "groupOrder": 4,
      "order": 3,
      "file": "library-building/reference/accessibility-and-linking.mdx",
      "section": "library-building"
    },
    "namespace-symbol-builder": {
      "slug": "namespace-symbol-builder",
      "title": "NamespaceSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 4,
      "file": "library-building/reference/namespace-symbol-builder.mdx",
      "section": "library-building"
    },
    "class-symbol-builder": {
      "slug": "class-symbol-builder",
      "title": "ClassSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 5,
      "file": "library-building/reference/class-symbol-builder.mdx",
      "section": "library-building"
    },
    "struct-symbol-builder": {
      "slug": "struct-symbol-builder",
      "title": "StructSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 6,
      "file": "library-building/reference/struct-symbol-builder.mdx",
      "section": "library-building"
    },
    "interface-symbol-builder": {
      "slug": "interface-symbol-builder",
      "title": "InterfaceSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 7,
      "file": "library-building/reference/interface-symbol-builder.mdx",
      "section": "library-building"
    },
    "enum-symbol-builder": {
      "slug": "enum-symbol-builder",
      "title": "EnumSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 8,
      "file": "library-building/reference/enum-symbol-builder.mdx",
      "section": "library-building"
    },
    "constructor-symbol-builder": {
      "slug": "constructor-symbol-builder",
      "title": "ConstructorSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 9,
      "file": "library-building/reference/constructor-symbol-builder.mdx",
      "section": "library-building"
    },
    "method-symbol-builder": {
      "slug": "method-symbol-builder",
      "title": "MethodSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 10,
      "file": "library-building/reference/method-symbol-builder.mdx",
      "section": "library-building"
    },
    "property-symbol-builder": {
      "slug": "property-symbol-builder",
      "title": "PropertySymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 11,
      "file": "library-building/reference/property-symbol-builder.mdx",
      "section": "library-building"
    },
    "indexer-symbol-builder": {
      "slug": "indexer-symbol-builder",
      "title": "IndexatorSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 12,
      "file": "library-building/reference/indexer-symbol-builder.mdx",
      "section": "library-building"
    },
    "operator-symbol-builder": {
      "slug": "operator-symbol-builder",
      "title": "OperatorSymbol Builder",
      "group": "Reference",
      "groupOrder": 4,
      "order": 13,
      "file": "library-building/reference/operator-symbol-builder.mdx",
      "section": "library-building"
    },
    "native-callback-helpers": {
      "slug": "native-callback-helpers",
      "title": "Native Callback Helpers",
      "group": "Reference",
      "groupOrder": 4,
      "order": 14,
      "file": "library-building/reference/native-callback-helpers.mdx",
      "section": "library-building"
    },
    "async-helpers-reference": {
      "slug": "async-helpers-reference",
      "title": "Async Helpers Reference",
      "group": "Reference",
      "groupOrder": 4,
      "order": 15,
      "file": "library-building/reference/async-helpers-reference.mdx",
      "section": "library-building"
    },
    "native-helpers-reference": {
      "slug": "native-helpers-reference",
      "title": "Native Helpers Reference",
      "group": "Reference",
      "groupOrder": 4,
      "order": 16,
      "file": "library-building/reference/native-helpers-reference.mdx",
      "section": "library-building"
    },
    "runtime-exception-reference": {
      "slug": "runtime-exception-reference",
      "title": "shard::runtime_exception",
      "group": "Reference",
      "groupOrder": 4,
      "order": 17,
      "file": "library-building/reference/runtime-exception-reference.mdx",
      "section": "library-building"
    },
    "the-shard-cli": {
      "slug": "the-shard-cli",
      "title": "The shard CLI",
      "group": "Build Your Project",
      "groupOrder": 6,
      "order": 1,
      "file": "build-your-project/01-the-shard-cli.mdx",
      "section": "build-your-project"
    },
    "project-configuration": {
      "slug": "project-configuration",
      "title": "Project Configuration",
      "group": "Build Your Project",
      "groupOrder": 6,
      "order": 2,
      "file": "build-your-project/02-project-configuration.mdx",
      "section": "build-your-project"
    },
    "package-management-with-geode": {
      "slug": "package-management-with-geode",
      "title": "Package Management with Geode",
      "group": "Build Your Project",
      "groupOrder": 6,
      "order": 3,
      "file": "build-your-project/03-package-management.mdx",
      "section": "build-your-project"
    },
    "library-search-paths": {
      "slug": "library-search-paths",
      "title": "Library Search Paths",
      "group": "Build Your Project",
      "groupOrder": 6,
      "order": 4,
      "file": "build-your-project/04-library-search-paths.mdx",
      "section": "build-your-project"
    },
    "compiler-pipeline": {
      "slug": "compiler-pipeline",
      "title": "Compiler Pipeline",
      "group": "Implementation Details",
      "groupOrder": 4,
      "order": 1,
      "file": "implementation-details/01-compiler-pipeline.mdx",
      "section": "implementation-details"
    },
    "bytecode-and-opcodes": {
      "slug": "bytecode-and-opcodes",
      "title": "Bytecode and OpCodes",
      "group": "Implementation Details",
      "groupOrder": 4,
      "order": 2,
      "file": "implementation-details/02-bytecode.mdx",
      "section": "implementation-details"
    },
    "virtual-machine-internals": {
      "slug": "virtual-machine-internals",
      "title": "Virtual Machine Internals",
      "group": "Implementation Details",
      "groupOrder": 4,
      "order": 3,
      "file": "implementation-details/03-virtual-machine.mdx",
      "section": "implementation-details"
    },
    "event-loop-and-libuv": {
      "slug": "event-loop-and-libuv",
      "title": "Event Loop and libuv",
      "group": "Implementation Details",
      "groupOrder": 4,
      "order": 4,
      "file": "implementation-details/04-event-loop.mdx",
      "section": "implementation-details"
    },
    "faq": {
      "slug": "faq",
      "title": "FAQ",
      "group": "FAQ",
      "groupOrder": 12,
      "order": 1,
      "file": "faq/01-index.mdx",
      "section": "faq"
    },
    "comparison-with-other-languages": {
      "slug": "comparison-with-other-languages",
      "title": "Comparison with Other Languages",
      "group": "FAQ",
      "groupOrder": 12,
      "order": 2,
      "file": "faq/02-comparison.mdx",
      "section": "faq"
    },
    "roadmap": {
      "slug": "roadmap",
      "title": "Roadmap",
      "group": "FAQ",
      "groupOrder": 12,
      "order": 4,
      "file": "faq/04-roadmap.mdx",
      "section": "faq"
    },
    "design-goals": {
      "slug": "design-goals",
      "title": "Design Goals",
      "group": "FAQ",
      "groupOrder": 12,
      "order": 5,
      "file": "faq/05-design-goals.mdx",
      "section": "faq"
    },
    "rejected-ideas": {
      "slug": "rejected-ideas",
      "title": "Rejected Ideas",
      "group": "FAQ",
      "groupOrder": 12,
      "order": 3,
      "file": "faq/03-rejected-ideas.mdx",
      "section": "faq"
    },
    "defer-and-idisposable": {
      "slug": "defer-and-idisposable",
      "title": "Defer and IDisposable",
      "group": "Common Language Features",
      "groupOrder": 4,
      "order": 10,
      "file": "common-language-features/10-defer-and-idisposable.mdx",
      "section": "common-language-features"
    }
  }
}

export default manifest
