import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import matter from 'gray-matter'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

export interface DocArticle {
  slug: string
  title: string
  group: string
  order: number
  file: string
  section: 'getting-started' | 'syntax' | 'stdlib'
}

export interface DocGroup {
  title: string
  items: { slug: string; title: string }[]
}

export interface DocManifest {
  'getting-started': DocGroup[]
  syntax: DocGroup[]
  stdlib: DocGroup[]
  articles: Record<string, DocArticle>
}

const docsRoot = path.resolve(__dirname, '../src/docs')
const outputPath = path.resolve(__dirname, '../src/docs/manifest.ts')

function scanDir(dir: string, section: 'getting-started' | 'syntax' | 'stdlib'): DocArticle[] {
  const articles: DocArticle[] = []

  function walk(current: string) {
    const entries = fs.readdirSync(current, { withFileTypes: true })
    for (const entry of entries) {
      const fullPath = path.join(current, entry.name)
      if (entry.isDirectory()) {
        walk(fullPath)
      } else if (entry.isFile() && entry.name.endsWith('.mdx')) {
        const raw = fs.readFileSync(fullPath, 'utf-8')
        const { data } = matter(raw)
        const relative = path.relative(docsRoot, fullPath).replace(/\\/g, '/')
        const slug = (data.slug as string) ?? entry.name.replace(/\.mdx$/, '')
        articles.push({
          slug,
          title: (data.title as string) ?? slug,
          group: (data.group as string) ?? 'Uncategorized',
          order: typeof data.order === 'number' ? data.order : 999,
          file: relative,
          section,
        })
      }
    }
  }

  walk(dir)
  return articles
}

function groupArticles(articles: DocArticle[]): DocGroup[] {
  const byGroup = new Map<string, DocArticle[]>()
  for (const article of articles) {
    const list = byGroup.get(article.group) ?? []
    list.push(article)
    byGroup.set(article.group, list)
  }

  const groups: DocGroup[] = []
  for (const [title, items] of byGroup) {
    items.sort((a, b) => a.order - b.order)
    groups.push({
      title,
      items: items.map((i) => ({ slug: i.slug, title: i.title })),
    })
  }

  // Stable sort by first order in each group
  groups.sort((a, b) => {
    const firstA = articles.find((x) => x.group === a.title)?.order ?? 999
    const firstB = articles.find((x) => x.group === b.title)?.order ?? 999
    return firstA - firstB
  })

  return groups
}

const gettingStartedArticles = scanDir(path.join(docsRoot, 'getting-started'), 'getting-started')
const syntaxArticles = scanDir(path.join(docsRoot, 'syntax'), 'syntax')
const stdlibArticles = scanDir(path.join(docsRoot, 'stdlib'), 'stdlib')
const allArticles = [...gettingStartedArticles, ...syntaxArticles, ...stdlibArticles]

const articlesRecord: Record<string, DocArticle> = {}
for (const article of allArticles) {
  articlesRecord[article.slug] = article
}

const manifest: DocManifest = {
  'getting-started': groupArticles(gettingStartedArticles),
  syntax: groupArticles(syntaxArticles),
  stdlib: groupArticles(stdlibArticles),
  articles: articlesRecord,
}

const fileContent = `// Auto-generated by scripts/build-docs-manifest.ts
// Do not edit manually.

export interface DocArticle {
  slug: string
  title: string
  group: string
  order: number
  file: string
  section: 'getting-started' | 'syntax' | 'stdlib'
}

export interface DocGroup {
  title: string
  items: { slug: string; title: string }[]
}

export interface DocManifest {
  'getting-started': DocGroup[]
  syntax: DocGroup[]
  stdlib: DocGroup[]
  articles: Record<string, DocArticle>
}

const manifest: DocManifest = ${JSON.stringify(manifest, null, 2)}

export default manifest
`

fs.writeFileSync(outputPath, fileContent)
console.log(`Docs manifest written to ${path.relative(process.cwd(), outputPath)} (${allArticles.length} articles)`)
